config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{omniauth_callbacks:'users/omniauth_callbacks'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#welcome'

  get '/auth/:provider/callback', to: 'omniauth#create'

  resources :users do
    resources :tickets
  end

  resources :users do
    resources :responses
  end

  resources :tickets, only: [:index,:show]

  resources :tickets do
    resources :responses
  end

  post '/tickets/:id', to: 'tickets#resolved'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/response.rb
class Response < ApplicationRecord
    belongs_to :user
    belongs_to :ticket

    validates :content, presence: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    belongs_to :user
    has_many :responses
    has_many :responded_users, through: :responses, source: :user

    validates :description, presence: true
    validates :content, presence: true

    scope :resolved, -> {where(is_resolved: true)}
    scope :not_resolved, -> {where(is_resolved: false)}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook]

  has_many :tickets
  has_many :responses
  has_many :ticket_respones, through: :tickets, source: :response
  has_many :responded_tickets, through: :responses, source: :ticket

  validates :name, presence: true
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    
    def after_sign_in_path_for(resource)
        user_path(current_user.id)
      end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
    before_action :find_response, only: [:edit,:update,:destroy]

    def new
       @ticket = Ticket.find_by(id: params[:ticket_id]) 
       @response = @ticket.responses.build
    end

    def create
        @ticket = Ticket.find_by(id: params[:ticket_id]) 
        @response = current_user.responses.build(response_params)
        if @response.save
            redirect_to ticket_path(@ticket)
        else
            render :new
        end
    end
    
    def find_response
        @response = Response.find_by(id: params[:id])
    end
    def show
        
    end
    def edit
        @ticket = Ticket.find_by(id: params[:ticket_id]) 
        @response = Response.find_by(id: params[:id])
    end

    def update
        if @response.update(response_params)
            redirect_to ticket_path(@response.ticket_id)
        else
            ale
            render :edit
        end
    end
    
    def destroy
        if @response.destroy
            redirect_to ticket_path(params[:ticket_id])
        end
    end

    
    private
    def response_params
        params.require(:response).permit(:content,:ticket_id)
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
    before_action :find_ticket, only: [:show,:edit,:update,:destroy,:resolved]

    def index
        @resolved = Ticket.resolved
        @not_resolved = Ticket.not_resolved
    end

    def new
     @ticket = Ticket.new   
    end
    
    def create
        @ticket = current_user.tickets.new(ticket_params)
        if @ticket.save
            redirect_to user_tickets_path(@ticket.id)
        else
            render :new
        end
    end

    def show
        @responses = @ticket.responses
    end

    def edit
        @ticket
    end

    def update
        if @ticket.update(ticket_params)
            redirect_to ticket_path(@ticket.id)
        else
            render :edit
        end
    end

    def destroy
        if @ticket.destroy
            redirect_to user_tickets_path(current_user.id)
        end
    end

    def find_ticket
        @ticket = Ticket.find_by(id: params[:id])
    end

    def resolved
        @ticket.is_resolved = true 
        @ticket.save
        redirect_to user_tickets_path(current_user.id), notice: "Ticket marked as resolved"
    end
    private
        def ticket_params
            params.require(:ticket).permit(:description,:content,:is_resolved)
        end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_rdata"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_ul
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user, only: [:index,:show]

    def signup
    end

    def show
    end 
    
    def index
        
    end

    def find_user
        @user = User.find_by(id: params[:id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def welcome
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(obj.errors.count, "error") %> prohibited this <%= obj.class.name%> from being saved:</h2>

  <ul>
  <% obj.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelpDeskRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="nav_bar">
        <ul>
          <% if current_user %>
            <p><%= button_to 'Sign Out', destroy_user_session_path , {method: 'delete'} %></p>
            <p><%= link_to 'Tickets',tickets_path%></p>
            <p><%= link_to "Home", user_path(current_user.id) %></p>
          <% end %>
      </ul>
      <%= yield %>
  </body>
</html>

app/views/responses/_form.html.erb
<%= render partial: 'layouts/errors', locals: {obj:@response} %>

<h2><%= current_user.email %></h2>
<%= form_for [@ticket,@response] do |f| %>
    <%= f.hidden_field :ticket_id %>
    <%= f.text_area :content %> <br>
    <%= f.submit %>
<% end %>

app/views/responses/edit.html.erb
<%= render @ticket %>
<%= render 'form' %>

app/views/responses/new.html.erb
<%= render @ticket %>
<%= render 'form' %>

app/views/tickets/_form.html.erb
<%= render partial: 'layouts/errors', locals: {obj:@ticket} %>


<%= form_for @ticket do |f|%>
    <%= f.label :description, 'Description' %>
    <%= f.text_field :description %> <br> <br>

    <%= f.label :content, 'Describe the problem' %>
    <%= f.text_area :content %> <br> <br>
    <%= f.hidden_field :is_resolved %>
    <%= f.submit %>
<% end %>

app/views/tickets/_ticket.html.erb
<h1><%= ticket.description %></h1>
<p>
    <%= ticket.content %>
</p>
<h3>Responses: </h3>
<% if !ticket.responses.empty?%>
    <ul>
        <% ticket.responses.each do |response| %>
            <% if response.persisted? %>
            <p><%= response.user.email %>: <%= response.content %></p>
                <% if response.user_id == current_user.id %>
            <p><%= link_to "Edit", edit_ticket_response_path(ticket.id,response.id) %>| <%= link_to "Delete", ticket_response_path(ticket.id,response.id),{method:'delete'} %>
                <% end %>
            <% end %>
        <% end %>
    </ul>
<% else %>
    <p>No Responses Found</p>
<% end %>
<% if @ticket.user_id == current_user.id %>
<p><%= link_to "Resolved", ticket_path(ticket.id),{method:'resolved'}%></p>
<% end %>

app/views/tickets/edit.html.erb
<%= render partial: 'layouts/errors', locals: {obj: @ticket} %>

<h1>Edit</h1>

<%= render 'form' %>

app/views/tickets/index.html.erb
<h1>Open Tickets</h1>
    <ul>
    <% @not_resolved.each do |ticket| %>
        <p><%= link_to ticket.description, ticket_path(ticket.id) %></p>
    <% end %>
    </ul>   

app/views/tickets/new.html.erb
<%= render partial: 'layouts/errors', locals: {obj:@ticket} %>

<h1>Create Ticket</h1>

<%= render 'form' %>

app/views/tickets/show.html.erb
<%= render @ticket %>

<p><%= link_to "Create Response", new_ticket_response_path(@ticket.id) %></p>
<% if @ticket.user_id == current_user.id && !@ticket.is_resolved %>
    <p><%= link_to 'Edit', edit_user_ticket_path(@ticket.user_id)%> | <%= link_to 'Delete', user_ticket_path(@ticket.user_id) ,{method:'delete'} %></p>
<% end %>

app/views/users/show.html.erb
<%= link_to "Create Ticket", new_user_ticket_path(current_user.id) %>

<h1>My Tickets</h1>
    <ul>
        <% if current_user.tickets.empty? %>
            <p>No Open Tickets </p>
        <% end %>
    <% current_user.tickets.each do |ticket| %>
        <% if ticket.is_resolved %>
            <p><%= ticket.description %> - Resolved</p>
        <% end %>
        <p><%= link_to ticket.description, ticket_path(ticket.id) %></p>
    <% end %>
        